/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubstancesRouteImport } from './routes/substances'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotfallRouteImport } from './routes/notfall'
import { Route as MixRouteImport } from './routes/mix'
import { Route as LogRouteImport } from './routes/log'
import { Route as KniggeRouteImport } from './routes/knigge'
import { Route as ErfahrungenRouteImport } from './routes/erfahrungen'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErfahrungenSlugRouteImport } from './routes/erfahrungen.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SubstancesRoute = SubstancesRouteImport.update({
  id: '/substances',
  path: '/substances',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotfallRoute = NotfallRouteImport.update({
  id: '/notfall',
  path: '/notfall',
  getParentRoute: () => rootRouteImport,
} as any)
const MixRoute = MixRouteImport.update({
  id: '/mix',
  path: '/mix',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const KniggeRoute = KniggeRouteImport.update({
  id: '/knigge',
  path: '/knigge',
  getParentRoute: () => rootRouteImport,
} as any)
const ErfahrungenRoute = ErfahrungenRouteImport.update({
  id: '/erfahrungen',
  path: '/erfahrungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErfahrungenSlugRoute = ErfahrungenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ErfahrungenRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/erfahrungen': typeof ErfahrungenRouteWithChildren
  '/knigge': typeof KniggeRoute
  '/log': typeof LogRoute
  '/mix': typeof MixRoute
  '/notfall': typeof NotfallRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risks': typeof RisksRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/substances': typeof SubstancesRoute
  '/api/chat': typeof ApiChatRoute
  '/erfahrungen/$slug': typeof ErfahrungenSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/erfahrungen': typeof ErfahrungenRouteWithChildren
  '/knigge': typeof KniggeRoute
  '/log': typeof LogRoute
  '/mix': typeof MixRoute
  '/notfall': typeof NotfallRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risks': typeof RisksRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/substances': typeof SubstancesRoute
  '/api/chat': typeof ApiChatRoute
  '/erfahrungen/$slug': typeof ErfahrungenSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/erfahrungen': typeof ErfahrungenRouteWithChildren
  '/knigge': typeof KniggeRoute
  '/log': typeof LogRoute
  '/mix': typeof MixRoute
  '/notfall': typeof NotfallRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risks': typeof RisksRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/substances': typeof SubstancesRoute
  '/api/chat': typeof ApiChatRoute
  '/erfahrungen/$slug': typeof ErfahrungenSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/erfahrungen'
    | '/knigge'
    | '/log'
    | '/mix'
    | '/notfall'
    | '/onboarding'
    | '/reset-password'
    | '/risks'
    | '/settings'
    | '/sitemap.xml'
    | '/stats'
    | '/substances'
    | '/api/chat'
    | '/erfahrungen/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/erfahrungen'
    | '/knigge'
    | '/log'
    | '/mix'
    | '/notfall'
    | '/onboarding'
    | '/reset-password'
    | '/risks'
    | '/settings'
    | '/sitemap.xml'
    | '/stats'
    | '/substances'
    | '/api/chat'
    | '/erfahrungen/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/erfahrungen'
    | '/knigge'
    | '/log'
    | '/mix'
    | '/notfall'
    | '/onboarding'
    | '/reset-password'
    | '/risks'
    | '/settings'
    | '/sitemap.xml'
    | '/stats'
    | '/substances'
    | '/api/chat'
    | '/erfahrungen/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  ErfahrungenRoute: typeof ErfahrungenRouteWithChildren
  KniggeRoute: typeof KniggeRoute
  LogRoute: typeof LogRoute
  MixRoute: typeof MixRoute
  NotfallRoute: typeof NotfallRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RisksRoute: typeof RisksRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  SubstancesRoute: typeof SubstancesRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/substances': {
      id: '/substances'
      path: '/substances'
      fullPath: '/substances'
      preLoaderRoute: typeof SubstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notfall': {
      id: '/notfall'
      path: '/notfall'
      fullPath: '/notfall'
      preLoaderRoute: typeof NotfallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mix': {
      id: '/mix'
      path: '/mix'
      fullPath: '/mix'
      preLoaderRoute: typeof MixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knigge': {
      id: '/knigge'
      path: '/knigge'
      fullPath: '/knigge'
      preLoaderRoute: typeof KniggeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erfahrungen': {
      id: '/erfahrungen'
      path: '/erfahrungen'
      fullPath: '/erfahrungen'
      preLoaderRoute: typeof ErfahrungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erfahrungen/$slug': {
      id: '/erfahrungen/$slug'
      path: '/$slug'
      fullPath: '/erfahrungen/$slug'
      preLoaderRoute: typeof ErfahrungenSlugRouteImport
      parentRoute: typeof ErfahrungenRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ErfahrungenRouteChildren {
  ErfahrungenSlugRoute: typeof ErfahrungenSlugRoute
}

const ErfahrungenRouteChildren: ErfahrungenRouteChildren = {
  ErfahrungenSlugRoute: ErfahrungenSlugRoute,
}

const ErfahrungenRouteWithChildren = ErfahrungenRoute._addFileChildren(
  ErfahrungenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  ErfahrungenRoute: ErfahrungenRouteWithChildren,
  KniggeRoute: KniggeRoute,
  LogRoute: LogRoute,
  MixRoute: MixRoute,
  NotfallRoute: NotfallRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RisksRoute: RisksRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  SubstancesRoute: SubstancesRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
