/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminDesignRouteImport } from './routes/admin-design'
import { Route as AdminKeyRouteImport } from './routes/admin-key'
import { Route as AftercareRouteImport } from './routes/aftercare'
import { Route as AkutRouteImport } from './routes/akut'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChecklisteRouteImport } from './routes/checkliste'
import { Route as DrugcheckingRouteImport } from './routes/drugchecking'
import { Route as InstallRouteImport } from './routes/install'
import { Route as KniggeRouteImport } from './routes/knigge'
import { Route as LogRouteImport } from './routes/log'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MixRouteImport } from './routes/mix'
import { Route as NotfallRouteImport } from './routes/notfall'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ReagenztestRouteImport } from './routes/reagenztest'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as SafetyPlanRouteImport } from './routes/safety-plan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SubstancesRouteImport } from './routes/substances'
import { Route as ToleranceRouteImport } from './routes/tolerance'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminChatRouteImport } from './routes/admin/chat'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as ApiAkutCoachRouteImport } from './routes/api/akut-coach'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiVoiceTokenRouteImport } from './routes/api/voice-token'
import { Route as ErfahrungenIndexRouteImport } from './routes/erfahrungen.index'
import { Route as ErfahrungenSlugRouteImport } from './routes/erfahrungen.$slug'
import { Route as ErfahrungenEinsendenRouteImport } from './routes/erfahrungen.einsenden'
import { Route as SessionActiveRouteImport } from './routes/session.active'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDesignRoute = AdminDesignRouteImport.update({
  id: '/admin-design',
  path: '/admin-design',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKeyRoute = AdminKeyRouteImport.update({
  id: '/admin-key',
  path: '/admin-key',
  getParentRoute: () => rootRouteImport,
} as any)
const AftercareRoute = AftercareRouteImport.update({
  id: '/aftercare',
  path: '/aftercare',
  getParentRoute: () => rootRouteImport,
} as any)
const AkutRoute = AkutRouteImport.update({
  id: '/akut',
  path: '/akut',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklisteRoute = ChecklisteRouteImport.update({
  id: '/checkliste',
  path: '/checkliste',
  getParentRoute: () => rootRouteImport,
} as any)
const DrugcheckingRoute = DrugcheckingRouteImport.update({
  id: '/drugchecking',
  path: '/drugchecking',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const KniggeRoute = KniggeRouteImport.update({
  id: '/knigge',
  path: '/knigge',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MixRoute = MixRouteImport.update({
  id: '/mix',
  path: '/mix',
  getParentRoute: () => rootRouteImport,
} as any)
const NotfallRoute = NotfallRouteImport.update({
  id: '/notfall',
  path: '/notfall',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ReagenztestRoute = ReagenztestRouteImport.update({
  id: '/reagenztest',
  path: '/reagenztest',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyPlanRoute = SafetyPlanRouteImport.update({
  id: '/safety-plan',
  path: '/safety-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SubstancesRoute = SubstancesRouteImport.update({
  id: '/substances',
  path: '/substances',
  getParentRoute: () => rootRouteImport,
} as any)
const ToleranceRoute = ToleranceRouteImport.update({
  id: '/tolerance',
  path: '/tolerance',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAkutCoachRoute = ApiAkutCoachRouteImport.update({
  id: '/api/akut-coach',
  path: '/api/akut-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTokenRoute = ApiVoiceTokenRouteImport.update({
  id: '/api/voice-token',
  path: '/api/voice-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ErfahrungenIndexRoute = ErfahrungenIndexRouteImport.update({
  id: '/erfahrungen/',
  path: '/erfahrungen/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErfahrungenSlugRoute = ErfahrungenSlugRouteImport.update({
  id: '/erfahrungen/$slug',
  path: '/erfahrungen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ErfahrungenEinsendenRoute = ErfahrungenEinsendenRouteImport.update({
  id: '/erfahrungen/einsenden',
  path: '/erfahrungen/einsenden',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionActiveRoute = SessionActiveRouteImport.update({
  id: '/session/active',
  path: '/session/active',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-design': typeof AdminDesignRoute
  '/admin-key': typeof AdminKeyRoute
  '/aftercare': typeof AftercareRoute
  '/akut': typeof AkutRoute
  '/chat': typeof ChatRoute
  '/checkliste': typeof ChecklisteRoute
  '/drugchecking': typeof DrugcheckingRoute
  '/install': typeof InstallRoute
  '/knigge': typeof KniggeRoute
  '/log': typeof LogRoute
  '/mcp': typeof McpRoute
  '/mix': typeof MixRoute
  '/notfall': typeof NotfallRoute
  '/onboarding': typeof OnboardingRoute
  '/reagenztest': typeof ReagenztestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risks': typeof RisksRoute
  '/safety-plan': typeof SafetyPlanRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/substances': typeof SubstancesRoute
  '/tolerance': typeof ToleranceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/akut-coach': typeof ApiAkutCoachRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/voice-token': typeof ApiVoiceTokenRoute
  '/erfahrungen/$slug': typeof ErfahrungenSlugRoute
  '/erfahrungen/einsenden': typeof ErfahrungenEinsendenRoute
  '/session/active': typeof SessionActiveRoute
  '/erfahrungen/': typeof ErfahrungenIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-design': typeof AdminDesignRoute
  '/admin-key': typeof AdminKeyRoute
  '/aftercare': typeof AftercareRoute
  '/akut': typeof AkutRoute
  '/chat': typeof ChatRoute
  '/checkliste': typeof ChecklisteRoute
  '/drugchecking': typeof DrugcheckingRoute
  '/install': typeof InstallRoute
  '/knigge': typeof KniggeRoute
  '/log': typeof LogRoute
  '/mcp': typeof McpRoute
  '/mix': typeof MixRoute
  '/notfall': typeof NotfallRoute
  '/onboarding': typeof OnboardingRoute
  '/reagenztest': typeof ReagenztestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risks': typeof RisksRoute
  '/safety-plan': typeof SafetyPlanRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/substances': typeof SubstancesRoute
  '/tolerance': typeof ToleranceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/akut-coach': typeof ApiAkutCoachRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/voice-token': typeof ApiVoiceTokenRoute
  '/erfahrungen/$slug': typeof ErfahrungenSlugRoute
  '/erfahrungen/einsenden': typeof ErfahrungenEinsendenRoute
  '/session/active': typeof SessionActiveRoute
  '/erfahrungen': typeof ErfahrungenIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-design': typeof AdminDesignRoute
  '/admin-key': typeof AdminKeyRoute
  '/aftercare': typeof AftercareRoute
  '/akut': typeof AkutRoute
  '/chat': typeof ChatRoute
  '/checkliste': typeof ChecklisteRoute
  '/drugchecking': typeof DrugcheckingRoute
  '/install': typeof InstallRoute
  '/knigge': typeof KniggeRoute
  '/log': typeof LogRoute
  '/mcp': typeof McpRoute
  '/mix': typeof MixRoute
  '/notfall': typeof NotfallRoute
  '/onboarding': typeof OnboardingRoute
  '/reagenztest': typeof ReagenztestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risks': typeof RisksRoute
  '/safety-plan': typeof SafetyPlanRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/substances': typeof SubstancesRoute
  '/tolerance': typeof ToleranceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/akut-coach': typeof ApiAkutCoachRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/voice-token': typeof ApiVoiceTokenRoute
  '/erfahrungen/$slug': typeof ErfahrungenSlugRoute
  '/erfahrungen/einsenden': typeof ErfahrungenEinsendenRoute
  '/session/active': typeof SessionActiveRoute
  '/erfahrungen/': typeof ErfahrungenIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-design'
    | '/admin-key'
    | '/aftercare'
    | '/akut'
    | '/chat'
    | '/checkliste'
    | '/drugchecking'
    | '/install'
    | '/knigge'
    | '/log'
    | '/mcp'
    | '/mix'
    | '/notfall'
    | '/onboarding'
    | '/reagenztest'
    | '/reset-password'
    | '/risks'
    | '/safety-plan'
    | '/settings'
    | '/sitemap.xml'
    | '/stats'
    | '/substances'
    | '/tolerance'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/chat'
    | '/admin/login'
    | '/admin/settings'
    | '/api/akut-coach'
    | '/api/chat'
    | '/api/tts'
    | '/api/voice-token'
    | '/erfahrungen/$slug'
    | '/erfahrungen/einsenden'
    | '/session/active'
    | '/erfahrungen/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-design'
    | '/admin-key'
    | '/aftercare'
    | '/akut'
    | '/chat'
    | '/checkliste'
    | '/drugchecking'
    | '/install'
    | '/knigge'
    | '/log'
    | '/mcp'
    | '/mix'
    | '/notfall'
    | '/onboarding'
    | '/reagenztest'
    | '/reset-password'
    | '/risks'
    | '/safety-plan'
    | '/settings'
    | '/sitemap.xml'
    | '/stats'
    | '/substances'
    | '/tolerance'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/chat'
    | '/admin/login'
    | '/admin/settings'
    | '/api/akut-coach'
    | '/api/chat'
    | '/api/tts'
    | '/api/voice-token'
    | '/erfahrungen/$slug'
    | '/erfahrungen/einsenden'
    | '/session/active'
    | '/erfahrungen'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/track'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-design'
    | '/admin-key'
    | '/aftercare'
    | '/akut'
    | '/chat'
    | '/checkliste'
    | '/drugchecking'
    | '/install'
    | '/knigge'
    | '/log'
    | '/mcp'
    | '/mix'
    | '/notfall'
    | '/onboarding'
    | '/reagenztest'
    | '/reset-password'
    | '/risks'
    | '/safety-plan'
    | '/settings'
    | '/sitemap.xml'
    | '/stats'
    | '/substances'
    | '/tolerance'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/chat'
    | '/admin/login'
    | '/admin/settings'
    | '/api/akut-coach'
    | '/api/chat'
    | '/api/tts'
    | '/api/voice-token'
    | '/erfahrungen/$slug'
    | '/erfahrungen/einsenden'
    | '/session/active'
    | '/erfahrungen/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminDesignRoute: typeof AdminDesignRoute
  AdminKeyRoute: typeof AdminKeyRoute
  AftercareRoute: typeof AftercareRoute
  AkutRoute: typeof AkutRoute
  ChatRoute: typeof ChatRoute
  ChecklisteRoute: typeof ChecklisteRoute
  DrugcheckingRoute: typeof DrugcheckingRoute
  InstallRoute: typeof InstallRoute
  KniggeRoute: typeof KniggeRoute
  LogRoute: typeof LogRoute
  McpRoute: typeof McpRoute
  MixRoute: typeof MixRoute
  NotfallRoute: typeof NotfallRoute
  OnboardingRoute: typeof OnboardingRoute
  ReagenztestRoute: typeof ReagenztestRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RisksRoute: typeof RisksRoute
  SafetyPlanRoute: typeof SafetyPlanRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  SubstancesRoute: typeof SubstancesRoute
  ToleranceRoute: typeof ToleranceRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAkutCoachRoute: typeof ApiAkutCoachRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiVoiceTokenRoute: typeof ApiVoiceTokenRoute
  ErfahrungenSlugRoute: typeof ErfahrungenSlugRoute
  ErfahrungenEinsendenRoute: typeof ErfahrungenEinsendenRoute
  SessionActiveRoute: typeof SessionActiveRoute
  ErfahrungenIndexRoute: typeof ErfahrungenIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-design': {
      id: '/admin-design'
      path: '/admin-design'
      fullPath: '/admin-design'
      preLoaderRoute: typeof AdminDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-key': {
      id: '/admin-key'
      path: '/admin-key'
      fullPath: '/admin-key'
      preLoaderRoute: typeof AdminKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aftercare': {
      id: '/aftercare'
      path: '/aftercare'
      fullPath: '/aftercare'
      preLoaderRoute: typeof AftercareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akut': {
      id: '/akut'
      path: '/akut'
      fullPath: '/akut'
      preLoaderRoute: typeof AkutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkliste': {
      id: '/checkliste'
      path: '/checkliste'
      fullPath: '/checkliste'
      preLoaderRoute: typeof ChecklisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drugchecking': {
      id: '/drugchecking'
      path: '/drugchecking'
      fullPath: '/drugchecking'
      preLoaderRoute: typeof DrugcheckingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knigge': {
      id: '/knigge'
      path: '/knigge'
      fullPath: '/knigge'
      preLoaderRoute: typeof KniggeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mix': {
      id: '/mix'
      path: '/mix'
      fullPath: '/mix'
      preLoaderRoute: typeof MixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notfall': {
      id: '/notfall'
      path: '/notfall'
      fullPath: '/notfall'
      preLoaderRoute: typeof NotfallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reagenztest': {
      id: '/reagenztest'
      path: '/reagenztest'
      fullPath: '/reagenztest'
      preLoaderRoute: typeof ReagenztestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-plan': {
      id: '/safety-plan'
      path: '/safety-plan'
      fullPath: '/safety-plan'
      preLoaderRoute: typeof SafetyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/substances': {
      id: '/substances'
      path: '/substances'
      fullPath: '/substances'
      preLoaderRoute: typeof SubstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tolerance': {
      id: '/tolerance'
      path: '/tolerance'
      fullPath: '/tolerance'
      preLoaderRoute: typeof ToleranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/akut-coach': {
      id: '/api/akut-coach'
      path: '/api/akut-coach'
      fullPath: '/api/akut-coach'
      preLoaderRoute: typeof ApiAkutCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice-token': {
      id: '/api/voice-token'
      path: '/api/voice-token'
      fullPath: '/api/voice-token'
      preLoaderRoute: typeof ApiVoiceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erfahrungen/': {
      id: '/erfahrungen/'
      path: '/erfahrungen'
      fullPath: '/erfahrungen/'
      preLoaderRoute: typeof ErfahrungenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erfahrungen/$slug': {
      id: '/erfahrungen/$slug'
      path: '/erfahrungen/$slug'
      fullPath: '/erfahrungen/$slug'
      preLoaderRoute: typeof ErfahrungenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erfahrungen/einsenden': {
      id: '/erfahrungen/einsenden'
      path: '/erfahrungen/einsenden'
      fullPath: '/erfahrungen/einsenden'
      preLoaderRoute: typeof ErfahrungenEinsendenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/active': {
      id: '/session/active'
      path: '/session/active'
      fullPath: '/session/active'
      preLoaderRoute: typeof SessionActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminChatRoute: typeof AdminChatRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatRoute: AdminChatRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminDesignRoute: AdminDesignRoute,
  AdminKeyRoute: AdminKeyRoute,
  AftercareRoute: AftercareRoute,
  AkutRoute: AkutRoute,
  ChatRoute: ChatRoute,
  ChecklisteRoute: ChecklisteRoute,
  DrugcheckingRoute: DrugcheckingRoute,
  InstallRoute: InstallRoute,
  KniggeRoute: KniggeRoute,
  LogRoute: LogRoute,
  McpRoute: McpRoute,
  MixRoute: MixRoute,
  NotfallRoute: NotfallRoute,
  OnboardingRoute: OnboardingRoute,
  ReagenztestRoute: ReagenztestRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RisksRoute: RisksRoute,
  SafetyPlanRoute: SafetyPlanRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  SubstancesRoute: SubstancesRoute,
  ToleranceRoute: ToleranceRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAkutCoachRoute: ApiAkutCoachRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiVoiceTokenRoute: ApiVoiceTokenRoute,
  ErfahrungenSlugRoute: ErfahrungenSlugRoute,
  ErfahrungenEinsendenRoute: ErfahrungenEinsendenRoute,
  SessionActiveRoute: SessionActiveRoute,
  ErfahrungenIndexRoute: ErfahrungenIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
