/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubstancesRouteImport } from './routes/substances'
import { Route as MixRouteImport } from './routes/mix'
import { Route as LogRouteImport } from './routes/log'
import { Route as IndexRouteImport } from './routes/index'

const SubstancesRoute = SubstancesRouteImport.update({
  id: '/substances',
  path: '/substances',
  getParentRoute: () => rootRouteImport,
} as any)
const MixRoute = MixRouteImport.update({
  id: '/mix',
  path: '/mix',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/mix': typeof MixRoute
  '/substances': typeof SubstancesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/mix': typeof MixRoute
  '/substances': typeof SubstancesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/mix': typeof MixRoute
  '/substances': typeof SubstancesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/log' | '/mix' | '/substances'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/log' | '/mix' | '/substances'
  id: '__root__' | '/' | '/log' | '/mix' | '/substances'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogRoute: typeof LogRoute
  MixRoute: typeof MixRoute
  SubstancesRoute: typeof SubstancesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/substances': {
      id: '/substances'
      path: '/substances'
      fullPath: '/substances'
      preLoaderRoute: typeof SubstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mix': {
      id: '/mix'
      path: '/mix'
      fullPath: '/mix'
      preLoaderRoute: typeof MixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogRoute: LogRoute,
  MixRoute: MixRoute,
  SubstancesRoute: SubstancesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
